CI: install pip packages before exporting zephyr cmake package
Since Zephyr 4.0, the command west packages pip --install must be run
before west zephyr-export.

Without this order, an error can occur when running west zephyr-export.

ModuleNotFoundError: No module named 'jsonschema'

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@foss.st.com>